/* wbfntime.h */

ERR FAR PASCAL WBFnNow( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnDay( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnWeekDay( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnMonth( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnYear( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnTimer( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnWakeup( int narg, LPVAR lparg, LPVAR lpResult );
