/* wbfnfile.h */

ERR FAR PASCAL WBFnFileCopy( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileDate( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileDelete( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileExist( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileIsOpen( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileLen( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileRename( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnFileSelect( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnGetAttr( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnSetAttr( int narg, LPVAR lparg, LPVAR lpResult );
ERR FAR PASCAL WBFnLoadFile( int narg, LPVAR lparg, LPVAR lpResult );
