//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WTLNETW.RC
//
#define IDD_LOGIN                       101
#define WTERR_UNEXPECTED_NETWORK        1000
#define WTERR_UNEXPECTED_ERR            1000
#define IDC_USERID                      1000
#define WTERR_INVALID_DRIVENUM          1001
#define IDC_PASSWORD                    1001
#define WTERR_ALREADY_ATTACHED          1002
#define WTERR_INVALID_NETDIR            1003
#define IDC_LOGINPROMPT                 1003
#define WTERR_NO_CONNECTION             1004
#define WTERR_DRIVE_BUSY                1005
#define WTERR_CANNOT_DETACH             1006
#define IDS_LOGIN_PROMPT                2000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
